version: '3'

services:
  proxy:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mysql.address=:3306"
    ports:
      - "80:80"
      - "1234:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./images/database/data_flight:/docker-entrypoint-initdb.d
    command: --max-allowed-packet=1000M

